version: v1

labels:
  # Issue Labels
  - label: 'Lifecycle: Frozen'
    matcher:
      comment: '/freeze'
  - label: 'Resolution: Fixed'
    matcher:
      comment: '/fixed'
  - label: 'Resolution: Partially Fixed'
    matcher:
      comment: '/partial'
  - label: 'Resolution: Deferred'
    matcher:
      comment: '/defer'
  - label: 'Resolution: Wont Fix'
    matcher:
      comment: '/no-fix'
  # PR Labels
  - label: 'PR - Review Status: Passed'
    matcher:
      comment: '/review-pass'
  - label: 'PR - Review Status: In Progress'
    matcher:
      comment: '/review-start'
  - label: 'PR - Review Status: Failed'
    matcher:
      comment: '/review-fail'
