# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.

name: Close Stale Issues
on:
  schedule:
  - cron: '0 0 * * *' 
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check for Stale Issues
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Number of days of inactivity before an Issue becomes stale
          days-before-issue-stale: 15
          
          # Number of days of inactivity before an Issue/Pull Request with the stale label is closed.
          # Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
          days-before-close: 7
          
          stale-issue-label: 'Lifecycle: Stale'
          
          # Issues with these labels will never be considered stale. Set to `[]` to disable
          exempt-issue-labels: 'Lifecycle: Frozen'
          
          # Label to remove when stale
          labels-to-remove-when-stale: 'Lifecycle: Active'

          # Label to remove when unstale
          labels-to-add-when-unstale: 'Lifecycle: Active'
          
          # Comment to post when marking as stale.
          stale-issue-message: >
              This issue has been automatically marked as stale because it has not had
              any recent activity. The issue will be auto-closed if no further activity occurs.

          # Comment to post when closing a stale Issue
          close-issue-message: >
              Closed due to inactivity. Thank you for your contributions.
